# https://docs.travis-ci.com/user/ci-environment/
# trusty - 7.5GB memory and 2 cores
sudo: required
dist: trusty

# travis performs a shallow clone by default, in case of any issues
# that requires full git history, enable this
# before_install: git fetch --unshallow

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

install: true

script: ./gradlew test installDist

